### ISSUE TITLE
White box attack not working

### ISSUE THREAD

**Issue by shubham-malaviya** [kabkabm/defensegan#6]
Hi,
I'm getting error after running the **whitbox.py** with the configuration given in the Readme file . I got the error at line **#210** "adv_x = attack_obj.generate(images_pl, **attack_params)". Please help me to solve this issue. Please note that blackbox.py is working fine. Here is the screenshot for the error.

![whitebox_error](https://user-images.githubusercontent.com/33419177/52032838-bcfbc380-2548-11e9-95b1-9141ab6144f9.png)

Thank you.

**Comment by shubham-malaviya** [comment]
I have solved the error. Seems like the problem was in the cleverhans Module. I changed a **cleverhans/attack_tf.py** file a little and everything worked fine.
Lines to change/update are : LINE #63 in **cleverhans/attack_tf.py**
grad = tf.gradients(loss, x)
grad = [grads if grads is not None else tf.zeros(x.shape[1:],dtype=tf.float32) for grads in grad]

**Comment by wuyunpeng666** [comment]
> I have solved the error. Seems like the problem was in the cleverhans Module. I changed a **cleverhans/attack_tf.py** file a little and everything worked fine.
> Lines to change/update are : LINE #63 in **cleverhans/attack_tf.py**
> grad = tf.gradients(loss, x)
> grad = [grads if grads is not None else tf.zeros(x.shape[1:],dtype=tf.float32) for grads in grad]
I got this problem long time.Thanks your method.
